# Generated by Django 5.1.1 on 2024-09-14 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewProductCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Text for the h3 tag (e.g., 'GET READY')",
                        max_length=100,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(help_text="Text for the h2 tag", max_length=200),
                ),
                ("description", models.TextField(help_text="Text for the p tag")),
                (
                    "link_url",
                    models.CharField(
                        help_text="URL for the card link (e.g., '/iphone-pre-order')",
                        max_length=200,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        help_text="Background image for the card",
                        upload_to="card_backgrounds/",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which the card should appear (lower numbers first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "New-Products Card",
                "verbose_name_plural": "New-Product Cards",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
